#!/bin/sh

# Make a copy of the settings file, just in case.
cp /etc/emoncms-hub/hub.conf /etc/emoncms-hub/hub.conf.bak`date +%s` 2>/dev/null

exit 0
                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~                                                                                                                                                           
~              
